Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from matplotlib import pyplot as plt

fig, (ax1,ax2,ax3) = plt.subplots(3, 1,
                                  sharex = False,
                                  sharey = False,
                                  figsize = (8,8))
fig.suptitle('IBIs detection') 

t = np.arange(0, len(ppg_filt)/fs,1.0/fs)

ax1.plot(t, ppg_filt, color = 'black')
ax1.scatter(t[0] + ppg_ibis_d2max/fs,
            ppg_filt[ppg_ibis_d2max],
            color = 'orange',
            marker = 'o')
ax1.set_ylabel('PPG [V]')
ax1.set_title('D2Max')

ax2.plot(t, ppg_filt, color = 'black')
ax2.scatter(t[0] + ppg_ibis_upslopes/fs,
            ppg_filt[ppg_ibis_upslopes],
            color = 'orange',
            marker = 'o')
ax2.set_ylabel('PPG [V]')
ax2.set_title('Upslopes')

ax3.plot(t, ppg_filt, color = 'black')
ax3.scatter(t[0] + ppg_ibis_delineator/fs,
            ppg_filt[ppg_ibis_delineator],
            color = 'orange',
            marker = 'o')
ax3.set_xlabel('Time [s]')
ax3.set_ylabel('PPG [V]')
ax3.set_title('Delineator')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[7], line 9[0m
[1;32m      3[0m fig, (ax1,ax2,ax3) [38;5;241m=[39m plt[38;5;241m.[39msubplots([38;5;241m3[39m, [38;5;241m1[39m,
[1;32m      4[0m                                   sharex [38;5;241m=[39m [38;5;28;01mFalse[39;00m,
[1;32m      5[0m                                   sharey [38;5;241m=[39m [38;5;28;01mFalse[39;00m,
[1;32m      6[0m                                   figsize [38;5;241m=[39m ([38;5;241m8[39m,[38;5;241m8[39m))
[1;32m      7[0m fig[38;5;241m.[39msuptitle([38;5;124m'[39m[38;5;124mIBIs detection[39m[38;5;124m'[39m) 
[0;32m----> 9[0m t [38;5;241m=[39m [43mnp[49m[38;5;241m.[39marange([38;5;241m0[39m, [38;5;28mlen[39m(ppg_filt)[38;5;241m/[39mfs,[38;5;241m1.0[39m[38;5;241m/[39mfs)
[1;32m     11[0m ax1[38;5;241m.[39mplot(t, ppg_filt, color [38;5;241m=[39m [38;5;124m'[39m[38;5;124mblack[39m[38;5;124m'[39m)
[1;32m     12[0m ax1[38;5;241m.[39mscatter(t[[38;5;241m0[39m] [38;5;241m+[39m ppg_ibis_d2max[38;5;241m/[39mfs,
[1;32m     13[0m             ppg_filt[ppg_ibis_d2max],
[1;32m     14[0m             color [38;5;241m=[39m [38;5;124m'[39m[38;5;124morange[39m[38;5;124m'[39m,
[1;32m     15[0m             marker [38;5;241m=[39m [38;5;124m'[39m[38;5;124mo[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'np' is not defined

